import type { Metadata } from "next";
<<<<<<< HEAD
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import BootstrapClient from "@/components/Book/BootstrapClient";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: 'Generated by create next app - Cams',
>>>>>>> RatingStar
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: Readonly<{
=======
}: Readonly <{
>>>>>>> RatingStar
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
      <body className={inter.className}>
        <BootstrapClient />
>>>>>>> RatingStar
        {children}
      </body>
    </html>
  );
}
