name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'   #changed version attempt to fix errors

      # Frontend Build
      - name: Navigate to Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm test             # Run frontend tests (ensure tests are defined)
          npm run build        # Build the frontend for production

      # Backend Build
      - name: Navigate to Backend
        working-directory: ./backend
        run: |
          npm install
          npm test             # Run backend tests
          npm run build        # Build the backend

      # Deployment Step to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # token created on repo secret
          vercel-args: '--prod'                      
